#!/usr/bin/env python3
import subprocess
import sys

def create_snapshot(snapshot_name):
    zfs_command = ["sudo", "zfs", "snapshot", "sa_pool/data@{}".format(snapshot_name)]
    subprocess.run(zfs_command)

def remove_snapshot(snapshot_name):
    if snapshot_name == "all":
        zfs_command = ["sudo", "zfs", "list", "-H", "-o", "name", "-t", "snapshot", "-r", "sa_pool/data"]
        snapshots = subprocess.check_output(zfs_command).decode().strip().split("\n")
        for snapshot in snapshots:
            subprocess.run(["sudo", "zfs", "destroy", snapshot])
    else:
        zfs_command = ["sudo", "zfs", "destroy", "sa_pool/data@{}".format(snapshot_name)]
        subprocess.run(zfs_command)

def list_snapshots():
    zfs_command = ["sudo", "zfs", "list", "-H", "-o", "name", "-t", "snapshot", "-r", "sa_pool/data"]
    snapshots = subprocess.check_output(zfs_command).decode().strip().split("\n")
    for snapshot in snapshots:
        print(snapshot)

def rollback_snapshot(snapshot_name):
    zfs_command = ["sudo", "zfs", "list", "-H", "-o", "name", "-t", "snapshot", "-r", "sa_pool/data"]
    snapshots = subprocess.check_output(zfs_command).decode().strip().split("\n")

    index = -1
    for i, snapshot in enumerate(snapshots):
        if snapshot.endswith("@{}".format(snapshot_name)):
            index = i
            break
    for snapshot in snapshots[index+1:]:
        subprocess.run(["sudo", "zfs", "destroy", snapshot])
    subprocess.run(["sudo", "zfs", "rollback", snapshots[index]])

def logrotate_zfs():
    logrotate_config = """/var/log/fakelog.log {
    rotate 10
    size 1k
    postrotate
    for i in $(seq 1 10); do
        if [ -e "/var/log/fakelog.log.$i" ]; then
            cp "/var/log/fakelog.log.$i" "/sa_data/log/fakelog.log.$i"
        fi
    done
    endscript
}"""
    with open("/tmp/logrotate_conf", "w") as f:
        f.write(logrotate_config)
    subprocess.run(["sudo", "logrotate", "/tmp/logrotate_conf"])
    subprocess.run(["rm", "/tmp/logrotate_conf"])


if __name__ == '__main__':
    command = sys.argv[1]
    if command == "help":
        print("Usage:\ncreate <snapshot-name>\nremove <snapshot-name> | all\nlist\nroll <snapshot-name>\nlogrotate")
        sys.exit()

    if command == "create":
        if len(sys.argv) < 3:
            sys.exit()
        create_snapshot(sys.argv[2])
    elif command == "remove":
        if len(sys.argv) < 3:
            sys.exit()
        remove_snapshot(sys.argv[2])
    elif command == "list":
        list_snapshots()
    elif command == "roll":
        if len(sys.argv) < 3:
            sys.exit()
        rollback_snapshot(sys.argv[2])
    elif command == "logrotate":
        logrotate_zfs()
    else:
        sys.exit()